import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import CartLength from './CartLength';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  

  return (
    <html lang="en">
      <body className={inter.className}>
      <header>
      <nav>
        <Link href="/admin">Admin</Link>
        <Link href="/credit">Credit</Link>
      </nav>
      <span>
        <Link href="/">4K clothes</Link>
      </span>
     <nav>
      <Link href="/addItem">Add Item</Link>
      <Link href="/sellItem">Sell Item</Link>
      <Link href="/cart"><CartLength/></Link>
     </nav>
    </header>
      {children}
      </body>
    </html>
  )
}
